### ISSUE TITLE
[Question] Can't the number of tiles in `SinusoidalCoordinate` be generalized?

### ISSUE THREAD

**Issue by ram-nad** [wildfirepy/wildfirepy-prerelease#10]

**Comment by Raahul-Singh** [comment]
[There are 460 non-fill tiles, tiles are 10 degrees by 10 degrees at the equator.
The tile coordinate system starts at (0,0) (horizontal tile number, vertical tile number) in the upper left corner and proceeds right (horizontal) and downward (vertical). The tile in the bottom right corner is (35,17).](https://modis-land.gsfc.nasa.gov/MODLAND_grid.html)

**Comment by Raahul-Singh** [comment]
So, not unless NASA changes it.
