### ISSUE TITLE
Fix importing modules.

### ISSUE THREAD

**Issue by Raahul-Singh** [wildfirepy/wildfirepy-prerelease#3]
There is some issue with importing the modules.
They do not work if the `cwd` is not `wildfirepy`.

**Comment by masterashu** [comment]
Let me see. 
I have dealt with import errors.

**Comment by Raahul-Singh** [comment]
The problem here is that all the modules work as long as I am in the base directory.
I believe that the problem lies with the fact that I don't know how to make modules :stuck_out_tongue:
We also need to figure out install issues.
It installs but on importing the modules aren't available.

**Comment by Raahul-Singh** [comment]
I'll assign this issue to you. Use your Django magic.
